spring.application.name=dinner-plan

# Default Profile (Change to 'mongo' to switch DB)
spring.profiles.active=mongo
spring.jmx.enabled=true
# Global Exclusion of JPA/DataSource (Managed explicitly by Profile Configs for SQL, disabled for Mongo)
# Global Exclusion of JPA/DataSource (Managed via @SpringBootApplication(excludeName=...) in Main class)
# spring.autoconfigure.exclude=... (Removed)

# Common Admin Configuration
app.admin.username=admin
app.admin.password=adminpassword
