spring.application.name=dinner-plan

# Default Profile (Change to 'mongo' to switch DB)
spring.profiles.active=mongo

# Common Admin Configuration
app.admin.username=admin
app.admin.password=adminpassword
